apiVersion: skaffold/v2alpha3
kind: Config
deploy: 
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: rommycy00/auth
      context: auth
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: rommycy00/client
      context: client
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: . 
    - image: rommycy00/tickets
      context: tickets
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: rommycy00/orders
      context: orders
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: rommycy00/expiration
      context: expiration
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: rommycy00/payments
      context: payments
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
